pipeline:

  publish_app:
    image: plugins/docker
    repo: suiqiu/tradingcenter
    dockerfile: Dockerfile
    secrets: [ docker_username, docker_password ]
    tags:
      - lastet
      - $$BRANCH
    when:
      branch: [ master ]
      event: push

  deploy:
    image: quay.io/honestbee/drone-kubernetes
    kubernetes_server: https://13.231.151.210:6443
    kubernetes_cert: ${KUBERNETES_CERT}
    kubernetes_token: ${KUBERNETES_TOKEN}
    namespace: ingress-nginx
    deployment: tradingcenter
    repo: suiqiu/tradingcenter
    container: tradingcenter
    tag: latest
