pipeline:
  staticfiles:
    image: python:2.7
    commands:
      - ls
      - sh deploy/collect_static.sh
      - pip install -r deploy/requirements.txt
      - python src/manage.py collectstatic --noinput
      - ls src/
  s3:
    image: plugins/s3
    commands:
      - ls
      - ls src/
    # bucket: my-bucket-name
    # access_key: a50d28f4dd477bc184fbd10b376de753
    # secret_key: bc5785d3ece6a9cdefa42eb99b58986f9095ff1c
    # source: public/**/*
    # target: /target/location
