pipeline:
  staticfiles:
    image: python:2.7
    commands:
      - ls
      - sh deploy/collect_static.sh
      - pip install -r deploy/requirements.txt
      - python src/manage.py collectstatic --noinput
      - ls src/
