workspace:
  base: /go
  path: src/github.com/drone/drone

pipeline:
  staticfiles:
    image: python:2.7
    commands:
      - pip install -r deploy/requirements.txt
      - python src/manage.py collectstatic -h
