pipeline:

  publish_app:
    image: plugins/docker
    repo: suiqiu/tradingcenter
    dockerfile: Dockerfile
    secrets: [ docker_username, docker_password ]
    tag: [ latest ]
    when:
      branch: 2.1
      event: push
