pipeline:

  publish_app:
    image: plugins/docker
    repo: suiqiu/tradingcenter
    dockerfile: Dockerfile
    secrets: [ docker_username, docker_password ]
    tags:
      - latest
      - ${DRONE_BRANCH}
    when:
      branch: [ master ]
      event: push

  deploy:
    image: quay.io/honestbee/drone-kubernetes
    secrets: [ KUBERNETES_SERVER, KUBERNETES_CERT, KUBERNETES_TOKEN ]
    namespace: ingress-nginx
    deployment: tradingcenter
    repo: suiqiu/tradingcenter
    container: tradingcenter
    tag: latest

  slack:
    image: plugins/slack
    webhook: ${{SLACK_WEBHOOK}}
    channel: drone-ci
    icon_url: https://unsplash.it/256/256/?random
    image_url: https://unsplash.it/256/256/?random
    template: >
      {{#success build.status}}
        Author: {{build.author}}, build {{build.number}} succeeded. Good job. {{build.commit}}
      {{else}}
        Author: {{build.author}}, build {{build.number}} failed. Fix me please. {{build.commit}}
      {{/success}}
